using System.Collections.Generic;

namespace KataSpeedProfilerModule {
    public static class FingerColourMapping {

        public static Dictionary<string, Fingers> FingerMapping = new Dictionary<string, Fingers>() {
            {"~", Fingers.LeftPinky },
            { "TAB", Fingers.LeftPinky },
            {"CAPS-LOCK", Fingers.LeftPinky  },
            {"SHIFT", Fingers.LeftPinky  },
            {"CTRL", Fingers.LeftPinky  },
            {"1", Fingers.LeftPinky  },
            {"2", Fingers.LeftPinky  },
            {"Q", Fingers.LeftPinky  },
            {"A", Fingers.LeftPinky  },
            {"Z", Fingers.LeftPinky  },
            {"ALT", Fingers.LeftPinky  },
            {"3", Fingers.LeftRing },
            {"W", Fingers.LeftRing },
            {"S", Fingers.LeftRing },
            {"X", Fingers.LeftRing },
            {"4", Fingers.LeftMiddle },
            {"E", Fingers.LeftMiddle },
            {"D", Fingers.LeftMiddle },
            {"C", Fingers.LeftMiddle },
            {"5", Fingers.LeftIndex },
            {"R", Fingers.LeftIndex },
            {"F", Fingers.LeftIndex },
            {"V", Fingers.LeftIndex },
            {"6", Fingers.LeftIndex },
            {"T", Fingers.LeftIndex },
            {"G", Fingers.LeftIndex },
            {"B", Fingers.LeftIndex },
            {"7", Fingers.RightIndex},
            {"Y", Fingers.RightIndex},
            {"H", Fingers.RightIndex},
            {"N", Fingers.RightIndex},
            {"8", Fingers.RightIndex},
            {"U", Fingers.RightIndex},
            {"J", Fingers.RightIndex},
            {"M", Fingers.RightIndex},
            {"9", Fingers.RightMiddle},
            {"I", Fingers.RightMiddle},
            {"K", Fingers.RightMiddle},
            {",", Fingers.RightMiddle},
            {"0", Fingers.RightRing},
            {"O", Fingers.RightRing},
            {"L", Fingers.RightRing},
            {".", Fingers.RightRing},
            {"-", Fingers.RightPinky},
            {"=", Fingers.RightPinky },
            {"BACKSPACE", Fingers.RightPinky },
            {"P",Fingers.RightPinky },
            {";", Fingers.RightPinky },
            {":", Fingers.RightPinky },
            {"/", Fingers.RightPinky },
            {"\\", Fingers.RightPinky },
            {"\'", Fingers.RightPinky },
            {"ENTER", Fingers.RightPinky },
            {"R.SHIFT", Fingers.RightPinky },
            {"R.ALT", Fingers.RightPinky },
            {"R.CTRL", Fingers.RightPinky },
            {"{", Fingers.RightPinky },
            {"}", Fingers.RightPinky },
            {"SPACE", Fingers.Thumb },
        };
    }
}
